# Generated by Django 2.2.6 on 2020-05-02 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('question', models.CharField(max_length=250, null=True)),
                ('publish_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100, null=True)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Submitted_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(null=True)),
                ('submit_date', models.DateField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Assignment')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Status2')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100, null=True)),
                ('institute_type', models.CharField(max_length=100, null=True)),
                ('expect_student', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=30, null=True)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Course')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Status')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instruct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Instructor'),
        ),
        migrations.CreateModel(
            name='Book_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30, null=True)),
                ('topic_file', models.FileField(null=True, upload_to='')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Course'),
        ),
    ]
